# ============================================================================
# Streamlit Configuration for Docker Deployment
# ============================================================================

[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = false
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false
